Rtc stats (#8)
* feat: Parse extra lobby reason waiting for host.

* feat(breakout-rooms): renaming

* ref(JingleSession) Always call sRD->cA-sLD for renegotiation.
For renegotiations triggered by the application, it is ok to execute sRD->cA-sLD cycle on the p2p initiator instead of executing cO->sLD->sRD cycle. Chrome sometimes creates a third m-line for p2p when createOffer is called which is unexpected and therefore it breaks the client's renegotiation cycle. This has been done in other places already, i.e., when remote sources are signaled, etc. so making it uniform across all renegotiations.

* fix(JingleSession) Modify encoding to stop/start outgoing media on p2p.
This is much faster than changing direction on the transceiver and doesn't need a renegotiation for the suspending/resuming media. Also fixes an issue with audio-only mode in p2p where media doesn't resume when audio-only mode is disabled if it was enabled while the jvb connection was active.

* fix(TPC): Make sure all RTCRtpSender:setParameters calls are sequential.
Recommit https://github.com/jitsi/lib-jitsi-meet/commit/17ade96a70971b7429b6beac73b919885e665f16 with the jvb leak fix.

* fix(codec-selection) Pick only 1 VP9 codec for p2p negotiation.
More than one VP9 payload type is produced in the offer, more experimental ones if the local endpoint has no local video source. Munge the SDP to remove all codecs besides the one with profile-id=0 so that only one VP9 codec is negotiated with p2p peer.

* fix(codecs): Enable VP9 encode on FF/Safari for p2p.
Addresses https://github.com/jitsi/jitsi-meet/issues/10657

* fix(RTC) Update docs w.r.t to config options.

* fix(SDP): Add msid to generated RTX SSRC only when present on primary SSRC.
Fixes setLocalDescription failing in the case where simulcast is disabled since the answer produced by the browser (after a local source is added) does not have the msid line.

* fix(ci) update action versions

* fix(misc) use safeJsonParse from js-utils

* fix(codec-selection): Do not remove codecs from capabilities.

* fix(IceFailedHandling): Attempt client reload when ICE restart via session-terminate fails.

* fix(JitsiConference): Filter local tracks when accepting remote p2p offer.

* fix(codec-selection): Disabled VP9 for p2p on Firefox.
When VP9 is at the top of the codec list in the remote offer, Firefox omits it in the answer but decides to use VP9 for encoding media. Therefore the remote peer gets an answer with no VP9 in the list and when it updates its local description (with no VP9) after a renegotiation, it stops rendering the VP9 video received from Firefox.

* fix(track.attach): return promise & improve logs

* feat(remoteTrack): log more container events

* feat: Sends machineId with the initial presence.

This is breaking xep-0045, but this is just between the client and prosody and will be added only when we send the initial conferenceIq via http.

* feat: Removes roomName field from moderator.

* feat: Moves moderator to be class.

* fix: Send visitors version when using http request.

* feat: Removes eventEmitter from Moderator.

It creates its own emitter now extending Listenable.

* feat: Moves moderator to xmpp.

* feat: Moves redirected event to connection events.

* fix: Fixes resolving disconnect if never connected.

* feat: Sends http conference-request before xmpp connecting.

* feat(rtcstats): move rtcstats to ljm (#2335)

* Added rtcstats

* increased webpack performance size warning to 830K

* Addressed most of Saghuls and Andrei's review comments.

* moved rtcstatsUseLibJitsi from analytics to testing

* refactor ljm rtcstats, use ljm conference events

* remove debug logs

* remove wrongly named files

* rename rtcstats module

* fix test

* address code review

* fix pack error

* address code review

---------

Co-authored-by: Nils Ohlmeier <github@ohlmeier.org>

* feat(iframe-api): replace ice servers

* feat(JitsiConference) drop unused transcription mechanism

It can be implemented at the application layer if desired.

* fix(JitsiConference) make sure leave always resolves

* fix: Fixes missing roomjid when sending sendConferenceRequest.

* fix: Fixes using correct reference in authenticateAndUpgradeRole.

This fixes changes from https://github.com/jitsi/lib-jitsi-meet/commit/1b5830f1bdc11a51aa1f475f68ebe12c12722e2f

* feat(auth) remove external auth mechanisms

* fix(ProxyConnectionPC) fake IQ acknowledgements

* fix(TPC): Revert the reverse ordering of encodings for Firefox 117 and newer.
In the older versions, the SSRCs in the SDP were in reversed order, i.e., the resolution order was 1:2:4 as opposed to Chromium and other browsers. Therefore, the client was confuguring the reverse order. However, the commit https://hg.mozilla.org/mozilla-central/rev/b0348f1f8d7197fb87158ba74542d28d46133997 which was seems to have landed in Firefox 117 has reverted the reversing of the RID order. Therefore, this hack is no longer needed on the newer Firefox versions.
This fixes an issue where the bridge suspends all video from Firefox to other endpoints in the call because of the reversed order of the encodings.

* feat: Enable TCC support on Firefox.
TCC was disabled on older versions because of a known issue where BWE is halved on every renegotiation. The regular libwebrtc updates in Firefox seems to have fixed it. This hopefully fixes the BWE issues seen on Firefox 117.

* fix(JingleSessionPC,ProxyConnectionPC) handle empty local tracks

When accepting a new offer.

* feat(local-track): log on mute.

* fix: getting right resolution for mobile web (#2356)

* chore: update js-utils with new ua-parser (#2358)

* fix: update engine version checking

* fix: allow rtcstats and watchrtc to coexists (#2360)

* chore(deps): update js-utils to 2.2.1

* fix: update rtcstats fix browser detection and relay obfuscation (#2362)

* feat: Do not advertise visitor version in case of jibri.

* log: Fix formatting of log message. (#2365)

* fix: Properly log remote track mute changes.

* fix(signaling): Merge ssrcOwners and _sourceName.

Additional benefits are:
 - ssrc -> source name will be updated on ssrc remap message from
 the bridge.
 - the map will be correctly cleaned when member leave (this logic was
 not working well for _sourceName map)
 - Looks cleaner and simpler.

* feat(jwt) expose JWT identity claims through

* fix(JingleSession) Use the video type from presence.
Instead of using the videoType from source map signaled by the bridge which can be incorrect if the bridge doesn't receive the presence before it sends out the source map. It uses the default 'camera' as video type if presence is not received from the senders. Possibly fixes a bug where a screenshare source is displayed in the wrong tile after the SSRC is re-mapped.

* feat(xmpp) remove support for the deprecated options.bosh

Yeah, > 4 years seems like ample time :-)

* Don't enqueue 'undefined' on the TransformStream if _decryptFrame fails. (#2376)

* fix(E2EE): Switch to VP8 when E2EE is enabled.
No other codecs are supported currently.

* fix(track): get track height (#2380)

* fix(track): get track height

* code review

* feat(RTCStats): Suppress unnecessary error message when rtcstatsEnabled === false (#2374)

* feat(RTCStats) Allow initializing without enabling

* feat(RTCStats) Simpler use of config properties

* feat(RTCStats) rollback property access level

* feat(RTCStats)revert to private and assert type

* fix(JingleSessionPC): call task callbacks upon clearing

* feat(visitors): Adds an option to request to be visitor.

* feat(ScreenObtainer): add more control over screen obtainer (#2371)

* feat(ScreenObtainer): add more control over screen obtainer

* fix(ScreenObtainer): fix constraints to select a preferential display surface

* fix(ScreenObtainer): remove Safari version check for displaySurface

* fix(ScreenObtainer): move all settings under screenShareSettings

* ref(JitsiConference): Cleanup code related to forceJVB121Ratio. (#2382)

* chore(deps-dev): bump @babel/traverse from 7.17.3 to 7.23.2

Bumps [@babel/traverse](https://github.com/babel/babel/tree/HEAD/packages/babel-traverse) from 7.17.3 to 7.23.2.
- [Release notes](https://github.com/babel/babel/releases)
- [Changelog](https://github.com/babel/babel/blob/main/CHANGELOG.md)
- [Commits](https://github.com/babel/babel/commits/v7.23.2/packages/babel-traverse)

---
updated-dependencies:
- dependency-name: "@babel/traverse"
  dependency-type: indirect
...

Signed-off-by: dependabot[bot] <support@github.com>

* fix(ScreenObtainer) Apply min fps after a successful gDM call. (#2383)

* fix(SS): Reverse the encoding order for Firefox desktop streams. (#2384)

Fixes an issue where screenshare from Firefox appears blurry on other endpoints in the call.

* Add SVC and Simulcast support for AV1 and VP9. (#2350)

Add SVC and Simulcast support for AV1 and VP9.

The default mode is the full SVC mode for VP9. It works as expected with the current version of JVB.
AV1 in the client is only supported when the bridge negotiates the Dependency Descriptor extension headers which are needed for reading the layer information for AV1 and H.264 video frames.

* feat: Enable H.264 simulcast support.
Multi-encoding simulcast for H.264 is supported now because of the DD header ext support added on the bridge side.

* fix(video-quality): Add default bitrates for all codecs.
Expect the videoQuality settings in the new format, deprecated configs are still supported.
videoQuality: {
    AV1: {
        maxBitratesVideo: {
            low: 100000,
            standard: 300000,
            high: 1000000,
            ssHigh: 1500000
        },
        useScalabilityModeAPI: {
            enabled: true,
            useSimulcast: true, //(defaults to SVC),
            useKSVC: true //(defaults to L3T3_KEY)
        },
    },
    H264: {
        maxBitratesVideo: {
            low: 200000,
            standard: 500000,
            high: 1500000,
            ssHigh: 2500000
        }
    },
    VP8: {
        maxBitratesVideo: {
            low: 200000,
            standard: 500000,
            high: 1500000,
            ssHigh: 2500000
        }
    },
    VP9: {
        maxBitratesVideo: {
            low: 100000,
            standard: 300000,
            high: 1200000,
            ssHigh: 2500000
        },
        useScalabilityModeAPI: {
            enabled: true,
            useSimulcast: true, //(defaults to SVC),
            useKSVC: true //(defaults to L3T3_KEY)
        },
    }
}

* Disable encodings when requested height for screenshare is 0.

* feat: add unit tests for scalability modes.

* ref: Move all encoding configuration calculation to TPCUtils.

* Add more unit tests for VP9 K-SVC mode.

* Make codec name in settings case insensitive.
Also read the deprecated max bitrates correctly, add unit tests to test it.

* ref(TPC): isSimulcastOn -> isSpatialScalabilityOn.
It makes more sense to call it spatial scalability than simulcast now that full SVC support is available.

* fix: Negotiate AV1 DD header exts only for AV1 and H.264.

* fix: Rename setting useL3T3Mode->useKSVC and adjust the defaults.

* ref(TPC): Rename variables related to DD header ext.

* feat: Retries joining the room on room creation error.

Fixes jitsi/jitsi-meet#13957.

* fix(kicked): leave the conference immediately

There is no reason to wait for for the event to be emitted.

* fix(sendFeedback): resolve if callstats disabled

* fix(TPCUtils) Insert simulcast recv line for all senders on FF.
The simulcast receive lines needs to be inserted in the receive desc for all the m-line associated with local tracks, currently its being done only for the first video source.

* ref(TPCUtils) Alpha sort the methods.

* fix(ssrc-rewriting) Update the track owner correctly.
Fixes an issue when the track owner is not updated after a p2p->jvb switch right after leaving breakout room.

* fix(codec-selection): Select VP8 as default codec.
When RTCRtpReceiver.getCapabilities() is not supported by browser or if it returns an empty list. Fixes an issue where call doesn't get established in Firefox ESR 102.
Fixes https://github.com/jitsi/jitsi-meet/issues/13839.

* feat(rtcstats): expose functionality to send identity data (#2393)

* fix(video-quality): Read the deprecated bitrate settings correctly.

* fix(video-quality): Set scaleResolutionDownBy value for every codec switch.
This fixes an issue when encodings for video streams are configured incorrectly after every codec switch

* fix(browser-detection): ipad detection in safari

* fix: Enable scalability mode on Chromium 113.

* chore(deps): bump rtcstats from 9.6.0 to 9.7.0 (#2401)

* Remove callstats support (#2399)

* ref: Remove PrecallTest.

* ref: Remove callstats support.

* fix: Double MUC_JOINED event.

When a self presence is received ( from mute or something else) during
leave operation, after presence unavailable is sent and before the final
presence unavaliable is received, we were interpreting it as muc joined
since the joined flag was immediately set to false.

* fix(Lobby): Clean the room on destroy.

* feat(analytics)connection time stats in join event

* fix(video-quality) Enable TCC support for Firefox 115 and later.
Firefox ESR 115 stops sending REMBs to the bridge under certain network conditions making the bridge suspend all video streams sent to the Firefox eps. It is still unclear why Firefox stops sending REMBs so enabling TCC support as workaround since TCC doesn't seem to have issues with uplink BWE in the older versions.

* feat(visitors): Fires events for received visitors message promotion … (#2403)

* feat(visitors): Fires events for received visitors message promotion request/response.

* squash: Updates logs.

* feat(RTC): add support for creating non-standard tracks (#2409)

* feat(RTC): add support for creating non-standard tracks

* fix(RTC): add additional checks for creating tracks via mediastream

* fix(RTC): simplify options to create track

* fix(RTC): fix tests

* fix(RTC): update sourceId documentation

* fix(AsyncQueue): call the callback only if it's defined (#2370)

* fix(GlobalOnErrorHandler) avoid calling it when we handle the error

* feat(GlobalOnErrorHandler) drop unused functions

They should never be needed if the error is handled, and if it isn't, it
will bubble up and end up in the handler anyway due to window.onerror.

* feat(GlobalOnErrorHandler) completely drop it

All modern browsers implement window.addEventListener for the 'error'
and 'unhandledrejection' listeners. Thus there is zero benefit from
using the legacy `onerror` handler here and rolling multiple handlers
ourselves.

There is an old config option `enableWindowOnErrorHandler` which was
never whitelisted in Jitsi Meet, so I'm 100% sure nobody is using it.

Even if someone was, migrarting to the above is simply better in every
possible way.

* fix(JitsiConference) don't fail hangup() if room wasn't created yet

Since there is nothing to do, pretend it all went well.

* fix(JitsiConference) simplify code

* Unify events and output single TypeScript declaration (#2407)

* fix(events): unify events to a single EventManager type, add support for single typescript declaration

* fix(lint): fix lint

* fix(events): fix incorrect instatiation

* fix(events): clean up redundant methods

* fix(events): keep EventEmitter name, alias NodeEventEmitter

* fix(events): fix loose reference

* fix(EventEmitter): remove on/off alias as redundant

* fix(RTCUtils): bring event handlers under class to use same event emitter

* fix(RTCUtils): fix lint

* fix(JitsiConference) remove unused functions

* fix(build) exclude generated types file from TSC build

* fix(RTC): reduce debug log noise

There is a lot of additional noise when log level is set to debug, the SDP descriptions should be set to trace (As it seems it was originally intended, based on the name of the variable)

* fix(Listenable) fix not adding cancellable listeners after refactor

* fix(types): fix last few types (#2417)

* #2387 Remove unused layers and width properties from kSimulcastFormats. Improve calculatePacketLoss function.  Avoid using string as keys in literal object creation syntax.

* fix(codec-selection): put Av1 support behind a flag.
Fixes an issue with audio after p2p->jvb switch when the media active state is set to false because of a setVideoCodecs call after a remote user joins the call.

* fix: Avoids p2p when there are visitors in the meeting.

* fix(ts) move dts file to types/

* fix(ts) don't declare types support yet

The generated dts file is slightly broken, and breaks upstream projects:

```
> jitsi-meet@0.0.0 tsc:native
> tsc --noEmit --project tsconfig.native.json

node_modules/lib-jitsi-meet/types/index.d.ts:3120:20 - error TS1005: '(' expected.

3120         constructor: typeof JitsiTrackError;
                        ~

node_modules/lib-jitsi-meet/types/index.d.ts:13832:20 - error TS1005: '(' expected.

13832         constructor: typeof JitsiConference;
                         ~
```

* rtc stats and remove local recording from smt

* added untracked files

* added untracked files

* added untracked files

* pre-compiled rtcstats

* pre-compiled rtcstats

* added distilled version of js-utils

* updated tags

* rebuild

* changed import path

* options for rtc stats

* added rtc stats websocket endpoint

---------

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: damencho <damencho@jitsi.org>
Co-authored-by: Werner Fleischer <70745309+wernf@users.noreply.github.com>
Co-authored-by: Jaya Allamsetty <jaya.allamsetty@8x8.com>
Co-authored-by: Saúl Ibarra Corretgé <s@saghul.net>
Co-authored-by: Hristo Terezov <hristo@jitsi.org>
Co-authored-by: Andrei Gavrilescu <51706180+andrei-gavrilescu@users.noreply.github.com>
Co-authored-by: Nils Ohlmeier <github@ohlmeier.org>
Co-authored-by: luocq3 <luocq3@asiainfo.com>
Co-authored-by: Saúl Ibarra Corretgé <saghul@jitsi.org>
Co-authored-by: Gabriel Borlea <gabriel.borlea@8x8.com>
Co-authored-by: bgrozev <boris@jitsi.org>
Co-authored-by: Jesse Gibson <10053423+PsychoLlama@users.noreply.github.com>
Co-authored-by: Jonathan Lennox <jonathan.lennox@8x8.com>
Co-authored-by: Andy Lee <a.lee.intl@gmail.com>
Co-authored-by: Auxane Thouary <32353355+athouary@users.noreply.github.com>
Co-authored-by: Daniel McAssey <DanielMcAssey@users.noreply.github.com>
Co-authored-by: Jaya Allamsetty <54324652+jallamsetty1@users.noreply.github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: Auxane Thouary <athouary@gmail.com>
Co-authored-by: Roman Melnyk <r.melnyk@smartrockstars.com>
Co-authored-by: brajendrak00068 <brajendrak00068>